export const APP_COLORS = {
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  TEXT_COLOR: '#F4F3F3',
  BUTTON_BACKGROUND: '#6832C4',
  BORDER_COLOR: '#8B71DB',
  BACKGROUND_COLOR: '#12082F',
  TEXT_INPUT_PLACEHOLDER_TEXT_COLOR: '#FFFFFF99',
  PLACEHOLDER_TEXT_COLOR: '#FFFFFF99',
  TEXT_INPUT_BORDER_COLOR: '#FFFFFF14',
  TEXT_INPUT_BACKGROUND_COLOR: '#12082F',
  THEME_DARK: 'white',
  IMAGE_BACKGROUND_COLOR: '#12082F',
};
